[package]
name = "bindings"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
windows = "0.19.0"

[build-dependencies]
regex = "1.5.4"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
thiserror = "1.0.26"
windows = "0.19.0"
