[package]
name = "webview2-com"
version = "0.1.0"
edition = "2018"
description = "Rust bindings for the WebView2 COM APIs"
repository = "https://github.com/wravery/webview2-rs"
license = "MIT"
keywords = [ "win32", "webview2" ]
categories = [ "os::windows-apis" ]

[dependencies]
bindings = { path = "../bindings", version = "0.1.0" }
callback-macros = { path = "../callback-macros", version = "0.1.0" }
windows = "0.19.0"

[dev-dependencies]
bindings = { path = "../bindings" }
regex = "1.5.4"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
windows = "0.19.0"
