[package]
name = "update-bindings"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
regex = "1.0"
thiserror = "1.0"

[dependencies.windows-bindgen]
version = "0.58"
features = [ "metadata" ]
